name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Build Tag Publish
        uses: bitovi/github-actions-docker-publish@v1.0.7
        with:
          use_sha: true
          checkout: true
          docker_username: blade2005
          docker_password: ${{ secrets.DOCKER_SECRET }}
          org_name: blade2005
          repo_name: ci-cd-image
          use_latest: true
        if: github.ref == 'refs/heads/main'
